### ISSUE TITLE
Permission to use advance configuration section

### ISSUE THREAD

**Issue by dhoer** [EMBL-EBI-TSI/cloud-portal-documentation#3]
The advanced configuration section in this is fantastic.  Can I get permission to add that section to git-secrets?  https://github.com/awslabs/git-secrets/pull/72

**Comment by giannidallatorre** [comment]
It’s a pleasure to hear that from you!
Feel free to add the section to git-secretes.

**Comment by hyandell** [comment]
Thank you Gianni. I'll take that as approval for us to publish it under Apache 2.0 License. Please let us know if that is an issue.
